// ==========================================
// TRANSLATION DICTIONARY (PT / EN / ES)
// ==========================================
export const t = {
  pt: {
    // Header & Meta
    title: "Gestão Corporativa de Operações Automotivas IA",
    subtitle: "Conselho de Manutenção, BI Integrado & Suporte Offline",
    developerEmail: "Operador:",
    roleSelector: "Nível de Acesso:",
    connectionState: "Rede:",
    online: "Conectado",
    offline: "Sem Sinal (Remoto)",
    simulateOffline: "Simular Sem Rede",
    simulateOnline: "Simular Online",
    mfaTitle: "Segurança MFA Ativa",
    mfaActive: "2FA Autenticado via SMS corporativo",
    language: "Idioma",

    // Roles
    roleAdmin: "Administrador / BI",
    roleManager: "Gerente Regional",
    roleTech: "Técnico de Campo",
    roleClient: "Área do Cliente",

    // Common Phrases
    pendingSync: "Aguardando Sincronização",
    syncSuccess: "Dados sincronizados com o BI Corporativo com sucesso!",
    syncingText: "Sincronizando dados offline...",
    searchVehicle: "Buscar veículo por Placa...",
    actions: "Ações",
    export: "Exportar Corporativo",
    exportExcel: "Exportar para Excel (CSV)",
    exportJSON: "Exportar para JSON BI",
    printReport: "Imprimir Relatório (PDF)",
    severity: "Severidade",
    supplier: "Fornecedor",
    status: "Status",
    date: "Data",
    cost: "Custo Estimado",
    save: "Salvar",
    cancel: "Cancelar",
    options: "Opções",

    // Technician Workspace
    dailyChecklist: "Checklist de Atividades Diárias (Obrigatório)",
    supplierChecklist: "Checklist de Visita a Fornecedores",
    diagnosticCenter: "Centro de Diagnóstico Assistido por IA",
    symptomsPlaceholder: "Descreva em detalhes os sintomas do veículo. Ex: Barulho metálico ao frear e leve perda de curso do pedal após rodar 50km...",
    runDiagnosis: "Solicitar Diagnóstico IA",
    uploadPhoto: "Anexar Foto de Peça/Falha",
    simulatedAudio: "Gravar Áudio de Sintomas de Falha",
    recordStart: "Gravar Relato por Voz",
    recordSec: "Gravando... Fale os sintomas do motor para transcrição.",
    photoPresets: "Amostras de Imagens de Falhas Automotivas",
    photoDented: "Velas de Ignição Carbonizadas",
    photoLeak: "Vazamento de Óleo no Cárter",
    photoBrake: "Pastilha de Freio no Limite",
    photoCrack: "Para-brisas Traseiro Rachado",
    diagnosticResult: "Diagnóstico Gerado via IA Server-Side",
    correctiveActions: "Ações Corretivas Recomendadas",
    preventiveActions: "Ações Preventivas de Longo Prazo",
    supplierCategory: "Classificação Corporativa do Fornecedor",
    budgetEstimator: "Orçamento Estimado das Operações",
    item: "Item",
    category: "Categoria",
    part: "Peça",
    labor: "Mão de Obra",
    bestPractices: "Melhores Práticas para Mitigar Gargalos",
    recentMaintenances: "Histórico Geral de Manutenções do Veículo",
    addLog: "Registrar Manutenção Manual",
    offlineLogAlert: "Você está offline. O log de manutenção foi adicionado à fila local e será transmitido automaticamente ao restaurar o sinal.",

    // Regional Manager Workspace
    regionalAnalysis: "Aba de Comunicação Regional & Gargalos",
    regions: "Região Central",
    regionalDashboard: "Análise de Gargalos por Divisão Administrativa",
    bottlenecks: "Gargalos Identificados em Tempo Real",
    bottlesNotes: "Propomos correções automáticas para filas saturadas ou demora no fornecimento de componentes críticos.",
    sendWhatsApp: "Enviar Alerta WhatsApp para Responsável",
    sendTeams: "Notificar via Webhook Teams",
    regionalTeamsSuccess: "Alerta de correção prioritária enviado ao canal do Microsoft Teams da regional com sucesso!",
    regionalWhatsAppSuccess: "Link do WhatsApp formatado na fila. Direcionando ao responsável regional...",
    corridorName: "Setor Regional de Conflito",
    bottleneckIssue: "Gargalo Crítico",
    bottleneckResolution: "Ação de Mitigação Sugerida",

    // Admin Workspace
    adminTitle: "Painel de Comando Executivo & BI Central",
    teamMetrics: "Métricas de Performance da Equipe Operacional",
    activeTechs: "Técnicos Ativos hoje",
    avgDiagTime: "Tempo Médio de Diagnóstico",
    faturamentoTotal: "Faturamento Faturado",
    inventTitle: "Gestão Integrada de Estoque de Autopeças",
    inventoryDesc: "As peças são debitadas automaticamente do estoque ao aprovar orçamentos. Peças abaixo do limite mínimo disparam reposições automáticas no fornecedor homologado.",
    replenishmentRecord: "Histórico de Reposições Automáticas Ativadas",
    partName: "Nome da Autopeça",
    quantity: "Qtd em Estoque",
    minLimit: "Limite Mínimo",
    linkedDealer: "Fornecedor Parceiro",
    reorderLevel: "Nível Crítico",
    reorderTriggered: "Reposição Automática Solicitada!",

    // Client Workspace
    clientPortal: "Área Segura do Proprietário do Veículo",
    viewAuthMFA: "Digite a Placa para consultar",
    activeDiagnosis: "Acompanhamento do seu Veículo",
    acceptBudget: "Aprovar Orçamento & Peças",
    rejectBudget: "Recusar Orçamento",
    clientPDFTitle: "Relatório Automatizado de Atendimento",
    printInvoiceHeader: "Fatura de Serviços de Manutenção Integrada - HENIZA TECH",
    paymentIntegration: "Integração via API de Gateway (Cartão/PIX)",
    payNow: "Enviar Link de Pagamento Externo",
    paymentSent: "Solicitação enviada para o gateway e-financeiro parceiro!",
    approvedSuccess: "Orçamento Aprovado! O estoque correspondente foi debitado e a peça já foi solicitada para o técnico.",

    // Audits Checklists
    supplierAuditTitle: "Checklist de Visita a Fornecedores (Mecânicas/Funilarias/Elétricas)",
    auditName: "Auditoria na Operação do Fornecedor",
    qualityCheck: "Verificou ferramentas profissionais e organização?",
    priceCheck: "Os preços praticados alinham com a tabela acordada?",
    auditSaved: "Relatório de Visita de Auditoria salvo!",

    // Tab Bar / Screens from Mobile App
    tabHome: "Início",
    tabScanner: "Scanner IA",
    tabBudgets: "Orçamentos",
    tabSchedule: "Agenda",
    tabParts: "Peças",
    tabConfig: "Config",

    // Extra New Labels
    welcomeBack: "Bem-vindo ao OficIA",
    diagnosticsCount: "Orçamentos",
    scheduledCount: "Agendados",
    runningCount: "Em Execução",
    missingPartsCount: "Peças Faltantes",
    financialReport: "Relatório Financeiro",
    financialFaturamento: "Faturamento: R$ 2.450,00 hoje",
    todaySchedule: "Agenda de Hoje",
    completed: "CONCLUÍDO",
    scheduled: "AGENDADO",
    addAppointment: "+ Novo Agendamento",
    customerName: "Nome do Cliente",
    vehicleModel: "Modelo do Veículo",
    time: "Horário",
    add: "Adicionar",
    enterpriseData: "Dados da Empresa",
    priceTable: "Tabela de Preços",
    generalData: "DADOS GERAIS",
    preferences: "PREFERÊNCIAS",
    notificationsToggle: "Notificações",
    autoBackupToggle: "Backup Automático",
    appVersion: "OficIA Sistema v1.0.0",
    devWithAi: "Desenvolvido com Inteligência Artificial"
  },
  en: {
    title: "AI Corporate Automotive Operations Management",
    subtitle: "Maintenance Panel, Integrated BI & Offline Support",
    developerEmail: "Operator:",
    roleSelector: "Access Rank:",
    connectionState: "Network:",
    online: "Connected",
    offline: "No Signal (Remote Loc.)",
    simulateOffline: "Go Offline",
    simulateOnline: "Go Online",
    mfaTitle: "Security MFA Enabled",
    mfaActive: "Authorized via 2FA Corporate SMS",
    language: "Language",

    roleAdmin: "Administrator / BI",
    roleManager: "Regional Lead",
    roleTech: "Field Technician",
    roleClient: "Client Space",

    pendingSync: "Pending Sync",
    syncSuccess: "Data synchronized to the Corporate BI portal successfully!",
    syncingText: "Syncing offline operations...",
    searchVehicle: "Search vehicle by Plate...",
    actions: "Actions",
    export: "Corporate Export",
    exportExcel: "Export as Excel (CSV)",
    exportJSON: "Export as JSON BI",
    printReport: "Print Report (PDF)",
    textPDFTitle: "Service Automated Summary Invoice",
    severity: "Severity",
    supplier: "Partner Supplier",
    status: "Status",
    date: "Date",
    cost: "Estimated Cost",
    save: "Save",
    cancel: "Cancel",
    options: "Options",

    dailyChecklist: "Required Daily Safety Checklist",
    supplierChecklist: "Supplier On-site Visit Checklist",
    diagnosticCenter: "AI Assisted Diagnosis Command Center",
    symptomsPlaceholder: "Detail symptoms here. Ex: Metallic rasping noises from front axle and soft brake pedal feel after 50 miles...",
    runDiagnosis: "Execute AI Diagnosis",
    uploadPhoto: "Attach Failure Photo",
    simulatedAudio: "Record Failure Symptoms Audio",
    recordStart: "Record Audio Symptom",
    recordSec: "Recording... Speak engine symptoms for transcription.",
    photoPresets: "Automotive Failure Image Presets",
    photoDented: "Carbon-Fouled Ignition Plugs",
    photoLeak: "Oil Sump Gasket Leakage",
    photoBrake: "Degraded Front Brake Pads",
    photoCrack: "Rear Windshield Damage",
    diagnosticResult: "Server-side Generated AI Diagnosis",
    correctiveActions: "Recommended Corrective Procedures",
    preventiveActions: "Long-term Prevention Guidelines",
    supplierCategory: "Recommended Supplier Market Division",
    budgetEstimator: "Estimated Operational Costing",
    item: "Item",
    category: "Category",
    part: "Part",
    labor: "Labor",
    bestPractices: "Operational Bottleneck Prevention Tips",
    recentMaintenances: "Vehicle Complete Service Logs",
    addLog: "Log Maintenance Manually",
    offlineLogAlert: "Device offline. Your entry was saved into the local syncing queue and will post when online.",

    regionalAnalysis: "Regional Communications & Bottlenecks",
    regions: "Central District",
    regionalDashboard: "Operations Bottleneck Division Console",
    bottlenecks: "Identified Regional Inefficiencies",
    bottlesNotes: "Automatic remediation plans generated for repair lines saturation and supplier delivery lagging.",
    sendWhatsApp: "Send WhatsApp Alert to Director",
    sendTeams: "Trigger Teams Webhook Alert",
    regionalTeamsSuccess: "Mitigation plan dispatched to Regional Microsoft Teams channel!",
    regionalWhatsAppSuccess: "WhatsApp template formatted. Routing dispatch link...",
    corridorName: "Regional Conflict Zone",
    bottleneckIssue: "Operational Inefficiency",
    bottleneckResolution: "AI Response Plan",

    adminTitle: "Executive Operations Console & BI Centre",
    teamMetrics: "Field Operations Real-Time Metrics",
    activeTechs: "Active Technicians",
    avgDiagTime: "Average Diagnose Time",
    faturamentoTotal: "Accrued Billed Operations",
    inventTitle: "Linked Inventory Logistics",
    inventoryDesc: "Approved quotes auto-deduct pieces from supply chain stocks. Low reserves dispatch automated restocking requests.",
    replenishmentRecord: "Automated Restocking Supply Queue",
    partName: "Spare Part Name",
    quantity: "Stock Level",
    minLimit: "Minimum Reserve",
    linkedDealer: "OEM Partner",
    reorderLevel: "Low Stock Warning",
    reorderTriggered: "Restocking Sent!",

    clientPortal: "Client Secure Vehicle Access Desk",
    viewAuthMFA: "Submit Plate to proceed",
    activeDiagnosis: "Live Car Repair Status Tracking",
    acceptBudget: "Approve Quote & Authorized Parts",
    rejectBudget: "Decline Quote",
    clientPDFTitle: "Service Automated Summary Invoice",
    printInvoiceHeader: "Service & Inventory Billing Report - HENIZA TECH",
    paymentIntegration: "Integrated Gateway API Payment Portal",
    payNow: "Send External Checkout Invoice",
    paymentSent: "Outgoing invoice request routed to credit gateway API!",
    approvedSuccess: "Quote approved! Stock units reserved and field technician notified.",

    supplierAuditTitle: "Supplier Visit Checklist (Mechanical/Bodywork/Electric)",
    auditName: "Audit on Supplier Operation",
    qualityCheck: "Verified professional tools & workshop order?",
    priceCheck: "Are active prices fully aligned with agreement?",
    auditSaved: "Audit Visit Report saved successfully!",

    // Tab Bar / Screens from Mobile App
    tabHome: "Home",
    tabScanner: "AI Scanner",
    tabBudgets: "Quotes",
    tabSchedule: "Schedule",
    tabParts: "Parts",
    tabConfig: "Config",

    // Extra New Labels
    welcomeBack: "Welcome to OficIA",
    diagnosticsCount: "Quotes",
    scheduledCount: "Scheduled",
    runningCount: "In Progress",
    missingPartsCount: "Missing Parts",
    financialReport: "Financial Report",
    financialFaturamento: "Revenue: $ 2,450.00 today",
    todaySchedule: "Today's Agenda",
    completed: "COMPLETED",
    scheduled: "SCHEDULED",
    addAppointment: "+ New Appointment",
    customerName: "Customer Name",
    vehicleModel: "Vehicle Model",
    time: "Time",
    add: "Add",
    enterpriseData: "Business Info",
    priceTable: "Price Table",
    generalData: "GENERAL DATA",
    preferences: "PREFERENCES",
    notificationsToggle: "Notifications",
    autoBackupToggle: "Auto Backup",
    appVersion: "OficIA System v1.0.0",
    devWithAi: "Developed with Artificial Intelligence"
  },
  es: {
    title: "Gestión Corporativa de Operación Automotriz IA",
    subtitle: "Tablero de Mantenimiento, BI Integrado y Soporte Offline",
    developerEmail: "Operador:",
    roleSelector: "Acceso Corporativo:",
    connectionState: "Red con:",
    online: "En Línea",
    offline: "Sin Señal (Local Remoto)",
    simulateOffline: "Simular Sin Red",
    simulateOnline: "Poner En Línea",
    mfaTitle: "Seguridad MFA Activa",
    mfaActive: "Autenticación 2FA vía SMS corporativo",
    language: "Idioma",

    roleAdmin: "Administrador / BI",
    roleManager: "Líder Regional",
    roleTech: "Técnico de Campo",
    roleClient: "Área de Clientes",

    pendingSync: "Sincronización Pendiente",
    syncSuccess: "¡Datos sincronizados al sistema BI de la corporación!",
    syncingText: "Sincronizando operaciones registradas...",
    searchVehicle: "Buscar placa del vehículo...",
    actions: "Acciones",
    export: "Exportación BI",
    exportExcel: "Exportar como Excel (CSV)",
    exportJSON: "Exportar como JSON BI",
    printReport: "Imprimir Factura (PDF)",
    severity: "Severidade",
    supplier: "Proveedor Asignado",
    status: "Estado",
    date: "Fecha",
    cost: "Costo Estimado",
    save: "Guardar",
    cancel: "Cancelar",
    options: "Opciones",

    dailyChecklist: "Lista de Verificación Diaria de Seguridad",
    supplierChecklist: "Auditoría en Visita a Proveedores",
    diagnosticCenter: "Mando de Diagnóstico Asistido por Inteligencia Artificial",
    symptomsPlaceholder: "Describa detalladamente las fallas del automóvil. Ej: Ruido metálico al frenar e inestabilidad en el pedal después de recorrer 50km...",
    runDiagnosis: "Correr Diagnóstico Inteligente",
    uploadPhoto: "Adjuntar Foto de Falla",
    simulatedAudio: "Grabar Audio de Síntomas",
    recordStart: "Iniciar Transmisión de Voz",
    recordSec: "Grabando... Hable las anomalías del motor para transcripción.",
    photoPresets: "Defectos de Componentes en Presets de Foto",
    photoDented: "Velas de Encendido Carbonizadas",
    photoLeak: "Goteo de Aceite del Cárter",
    photoBrake: "Desgaste Límite Pastilla de Freno",
    photoCrack: "Fisura en Parabrisas Trasero",
    diagnosticResult: "Diagnóstico Generado vía Inteligencia Artificial",
    correctiveActions: "領 Mecánica Recomendada",
    preventiveActions: "Lineamientos de Prevención de Fallas",
    supplierCategory: "Categoría de Taller de Proveeduría",
    budgetEstimator: "Estimación Presupuestal Detallada",
    item: "Componente",
    category: "Categoría",
    part: "Repuesto/Pieza",
    labor: "Mano de Obra",
    bestPractices: "Consejos Preventivos Especializados",
    recentMaintenances: "Historial de Mantenimientos del Vehículo",
    addLog: "Registrar Reparación Manual",
    offlineLogAlert: "Registrado fuera de línea. La acción se colocó en cola de sincronización para cuando retorne la conexión.",

    regionalAnalysis: "Comunicaciones Regionales y Cuellos de Botella",
    regions: "Sector Central",
    regionalDashboard: "Módulo Gestor de Cuellos de Botella",
    bottlenecks: "Demoras de Proveeduría Operativa",
    bottlesNotes: "Soluciones y planes paliativos inteligentes para subsanar faltantes de repuestos o talleres saturados.",
    sendWhatsApp: "Enviar Directriz de WhatsApp al Director",
    sendTeams: "Notificar por Canal de Teams Webhook",
    regionalTeamsSuccess: "¡Plan de remediación enviado con éxito al canal oficial de Microsoft Teams!",
    regionalWhatsAppSuccess: "Estructura del WhatsApp guardada. Redirigiendo al enlace de despacho...",
    corridorName: "Área de Operación Regional",
    bottleneckIssue: "Ineficiencia Logística",
    bottleneckResolution: "Solución Recomendada por IA",

    adminTitle: "Estación Ejecutiva y Análisis Corporativo de BI",
    teamMetrics: "Indicadores de Productividad del Equipo",
    activeTechs: "Mecánicos / Técnicos en Turno",
    avgDiagTime: "Retraso Medio en Diagnósticos",
    faturamentoTotal: "Total Facturado Operativo",
    inventTitle: "Logística y Cadena de Suministro de Repuestos",
    inventoryDesc: "La aprobación de presupuestos reduce unidades de repuesto. Se gatilla reposición automática en caso de reserva crítica de stock.",
    replenishmentRecord: "Historial de Solicitudes de Surtido Automático",
    partName: "Nombre del Elemento",
    quantity: "Existencia",
    minLimit: "Mínimo de Operaciones",
    linkedDealer: "OEM Dealer Autorizado",
    reorderLevel: "Nivel de Peligro",
    reorderTriggered: "¡Reabastecimiento Solicitado con Éxito!",

    clientPortal: "Acceso Privado para el Cliente",
    viewAuthMFA: "Digite la Placa para Consultar",
    activeDiagnosis: "Seguimiento en Vivo del Vehículo",
    acceptBudget: "Autorizar Presupuesto y Piezas",
    rejectBudget: "Rechazar Cotización",
    clientPDFTitle: "Factura Resumida Certificada de Atenciones",
    printInvoiceHeader: "Ficha Integrada de Inventario y Operación - HENIZA TECH",
    paymentIntegration: "Pasarela Segura Financiera Externa",
    payNow: "Enviar Vínculo de Cobro Externa",
    paymentSent: "¡Cobro enviado a la pasarela financiera externa homologada!",
    approvedSuccess: "¡Cotización admitida! Repuestos reservados para el equipo técnico regional.",

    supplierAuditTitle: "Ficha de Visita al Proveedor (Mecánica/Carrocería/Eléctrico)",
    auditName: "Auditoría de Operaciones del Proveedor",
    qualityCheck: "¿Se verificaron herramientas profesionales y orden?",
    priceCheck: "¿Precios alineados con el acuerdo comercial?",
    auditSaved: "¡Ficha de Visita de Auditoría guardada con éxito!",

    // Tab Bar / Screens from Mobile App
    tabHome: "Inicio",
    tabScanner: "Scanner IA",
    tabBudgets: "Cotizaciones",
    tabSchedule: "Agenda",
    tabParts: "Piezas",
    tabConfig: "Config",

    // Extra New Labels
    welcomeBack: "Bienvenido a OficIA",
    diagnosticsCount: "Cotizaciones",
    scheduledCount: "Agendados",
    runningCount: "En Progreso",
    missingPartsCount: "Piezas Faltantes",
    financialReport: "Informe Financiero",
    financialFaturamento: "Facturación: R$ 2.450,00 hoy",
    todaySchedule: "Agenda de Hoy",
    completed: "COMPLETADO",
    scheduled: "AGENDADO",
    addAppointment: "+ Nuevo Turno",
    customerName: "Nombre del Cliente",
    vehicleModel: "Modelo del Vehículo",
    time: "Horario",
    add: "Añadir",
    enterpriseData: "Datos de Empresa",
    priceTable: "Lista de Precios",
    generalData: "DATOS GENERALES",
    preferences: "PREFERENCIAS",
    notificationsToggle: "Notificaciones",
    autoBackupToggle: "Copia Automática",
    appVersion: "OficIA Sistema v1.0.0",
    devWithAi: "Desarrollado con Inteligencia Artificial"
  }
};

export type SelectedLang = 'pt' | 'en' | 'es';

export const INITIAL_VEHICLES = [
  { plate: "ABC-1234", model: "Volkswagen Gol 1.0 GTI - 2021", status: "Pronto" },
  { plate: "XYZ-9876", model: "Chevrolet Onix 1.4 LTZ Turbo - 2023", status: "Em Diagnóstico" },
  { plate: "KJZ-5522", model: "Ford Ka 1.5 SE Sedan - 2022", status: "Manutenção Pendente" },
  { plate: "EAL-4040", model: "Toyota Corolla Hybrid Extreme - 2024", status: "Diagnóstico Pronto" }
];

export const INITIAL_INVENTORY = [
  { id: "1", namePt: "Filtro de Ar de Performance", nameEn: "Performance Air Filter", nameEs: "Filtro de Aire Premium", stock: 12, min: 5, supplier: "Mecânica Precision", price: 120.00 },
  { id: "2", namePt: "Jogo de Velas Iridium Sênior", nameEn: "Set of Iridium Ignition Plugs", nameEs: "Juego de Velas Iridio", stock: 18, min: 8, supplier: "PowerVolt Elétrica", price: 280.00 },
  { id: "3", namePt: "Bateria Blindada 60Ah Heliar", nameEn: "Armed 60Ah Heliar Battery", nameEs: "Batería Blindada 60Ah Heliar", stock: 3, min: 4, supplier: "Auto-Elétrica Faísca", price: 540.00 },
  { id: "4", namePt: "Kit Pastilhas de Freio Orgânicas", nameEn: "Organic Brake Pads Kit", nameEs: "Juego Pastillas de Freno Orgánicas", stock: 15, min: 6, supplier: "Concessionária Roma Fiat", price: 160.00 },
  { id: "5", namePt: "Kit Amortecedor Monroe Turbo", nameEn: "Monroe Turbo Absorber Kit", nameEs: "Kit Amortiguador Monroe Turbo", stock: 2, min: 3, supplier: "Auto Centro Pro", price: 780.00 }
];

export const INITIAL_HISTORIES = [
  { id: "101", plate: "ABC-1234", problem: "Suspensão ruidosa ao rodar em vias irregulares", date: "2026-05-10", supplier: "Auto Centro Pro", status: "Completa", cost: 1200.00 },
  { id: "102", plate: "XYZ-9876", problem: "Luz de injeção acesa constante após abastecer", date: "2026-05-18", supplier: "Mecânica Precision", status: "Em Analise", cost: 450.00 },
  { id: "103", plate: "KJZ-5522", problem: "Vidro elétrico dianteiro esquerdo parou de responder", date: "2026-05-20", supplier: "Auto-Elétrica Faísca", status: "Pendente", cost: 320.00 }
];

export const INITIAL_BOTTLENECK_CASES = [
  { area: "Região Metropolitana SP", issue: "Atraso no reabastecimento de juntas de cabeçote com a Concessionária Roma", solution: "Gargalo reduzido em 35% ao credenciar o distribuidor rápido 'Paraná Autopeças'." },
  { area: "Regional Sul", issue: "Saturação das funilarias locais com tempo de espera superior a 7 dias úteis", solution: "Direcionar avarias categoria Média para 'Especializada Silva' com prioridade acordada por convênio." },
  { area: "Logística Fluvial Norte", issue: "Falta de baterias em áreas portuárias offline", solution: "Manter estoque estratégico avançado redundante (min +150%) sincronizado via app offline local." }
];

export const PRESETS = [
  { nameKey: "photoDented", file: "velas_carbono", mockPath: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=400&q=80", label: "Velas de Ignição" },
  { nameKey: "photoLeak", file: "vazamento_oleo", mockPath: "https://images.unsplash.com/photo-1517524008436-a38717a33d99?auto=format&fit=crop&w=400&q=80", label: "Goteira no Cárter" },
  { nameKey: "photoBrake", file: "pastilha_freio", mockPath: "https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=400&q=80", label: "Desgaste Freios" },
  { nameKey: "photoCrack", file: "parabrisas", mockPath: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=400&q=80", label: "Trinca no Vidro" }
];

export const INITIAL_MOBILE_BUDGETS = [
  { id: '1', cliente: 'Carlos Mendes', veiculo: 'Toyota Corolla', valor: 'R$ 460,00', status: 'Em Andamento' },
  { id: '2', cliente: 'Ana Souza', veiculo: 'Honda Civic', valor: 'R$ 355,00', status: 'Pendente' },
  { id: '3', cliente: 'Roberto Lima', veiculo: 'VW Gol', valor: 'R$ 210,00', status: 'Concluído' },
  { id: '4', cliente: 'Marcos Silva', veiculo: 'Fiat Uno', valor: 'R$ 180,00', status: 'Aprovado' },
];

export const INITIAL_AGENDA_EVENTS = [
  { id: '1', hora: '08:00', titulo: 'Revisão Completa', dados: 'João Paulo • Ford Ka • ABC-1234', status: 'CONFIRMADO' },
  { id: '2', hora: '10:30', titulo: 'Troca de Embreagem', dados: 'Maria Clara • Hyundai HB20 • DEF-5678', status: 'AGUARDANDO' },
  { id: '3', hora: '14:00', titulo: 'Alinhamento e Balanceamento', dados: 'Carlos Alberto • Fiat Argo • GHI-9012', status: 'CHEGOU' },
];

export const MOBILE_PIECE_STOCKS = [
  { id: '1', nome: 'Filtro de Óleo', estoque: 12, min: 5, status: 'OK' },
  { id: '2', nome: 'Pastilha de Freio', estoque: 3, min: 4, status: 'BAIXO' },
  { id: '3', nome: 'Correia Dentada', estoque: 7, min: 3, status: 'OK' },
  { id: '4', nome: 'Óleo Motor 5W30', estoque: 2, min: 6, status: 'CRÍTICO' },
];

export const PRICE_TABLE_ITEMS = [
  { service: "Alinhamento 3D + Balanceamento", price: 150.00 },
  { service: "Troca de Óleo de Motor (Lubrax Sintético)", price: 280.00 },
  { service: "Troca de Pastilhas de Freio Orgânicas", price: 180.00 },
  { service: "Revisão Geral e Check-up 60 Pontos", price: 350.00 },
  { service: "Troca de Embreagem Completa", price: 980.00 },
];
